/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesIndexRouteImport } from './routes/sites/index'
import { Route as SitesSiteIdRouteImport } from './routes/sites/$siteId'
import { Route as SitesSiteIdIndexRouteImport } from './routes/sites/$siteId/index'
import { Route as SitesSiteIdActivityRouteImport } from './routes/sites/$siteId/activity'
import { Route as SitesSiteIdRulesRouteImport } from './routes/sites/$siteId/rules'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIndexRoute = SitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdRoute = SitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdIndexRoute = SitesSiteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SitesSiteIdRoute,
} as any)
const SitesSiteIdActivityRoute = SitesSiteIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => SitesSiteIdRoute,
} as any)
const SitesSiteIdRulesRoute = SitesSiteIdRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => SitesSiteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sites/$siteId': typeof SitesSiteIdRouteWithChildren
  '/sites/': typeof SitesIndexRoute
  '/sites/$siteId/activity': typeof SitesSiteIdActivityRoute
  '/sites/$siteId/rules': typeof SitesSiteIdRulesRoute
  '/sites/$siteId/': typeof SitesSiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sites': typeof SitesIndexRoute
  '/sites/$siteId/activity': typeof SitesSiteIdActivityRoute
  '/sites/$siteId/rules': typeof SitesSiteIdRulesRoute
  '/sites/$siteId': typeof SitesSiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sites/$siteId': typeof SitesSiteIdRouteWithChildren
  '/sites/': typeof SitesIndexRoute
  '/sites/$siteId/activity': typeof SitesSiteIdActivityRoute
  '/sites/$siteId/rules': typeof SitesSiteIdRulesRoute
  '/sites/$siteId/': typeof SitesSiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sites/$siteId'
    | '/sites/'
    | '/sites/$siteId/activity'
    | '/sites/$siteId/rules'
    | '/sites/$siteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sites'
    | '/sites/$siteId/activity'
    | '/sites/$siteId/rules'
    | '/sites/$siteId'
  id:
    | '__root__'
    | '/'
    | '/sites/$siteId'
    | '/sites/'
    | '/sites/$siteId/activity'
    | '/sites/$siteId/rules'
    | '/sites/$siteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitesSiteIdRoute: typeof SitesSiteIdRouteWithChildren
  SitesIndexRoute: typeof SitesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/': {
      id: '/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof SitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId/': {
      id: '/sites/$siteId/'
      path: '/'
      fullPath: '/sites/$siteId/'
      preLoaderRoute: typeof SitesSiteIdIndexRouteImport
      parentRoute: typeof SitesSiteIdRoute
    }
    '/sites/$siteId/activity': {
      id: '/sites/$siteId/activity'
      path: '/activity'
      fullPath: '/sites/$siteId/activity'
      preLoaderRoute: typeof SitesSiteIdActivityRouteImport
      parentRoute: typeof SitesSiteIdRoute
    }
    '/sites/$siteId/rules': {
      id: '/sites/$siteId/rules'
      path: '/rules'
      fullPath: '/sites/$siteId/rules'
      preLoaderRoute: typeof SitesSiteIdRulesRouteImport
      parentRoute: typeof SitesSiteIdRoute
    }
  }
}

interface SitesSiteIdRouteChildren {
  SitesSiteIdActivityRoute: typeof SitesSiteIdActivityRoute
  SitesSiteIdRulesRoute: typeof SitesSiteIdRulesRoute
  SitesSiteIdIndexRoute: typeof SitesSiteIdIndexRoute
}

const SitesSiteIdRouteChildren: SitesSiteIdRouteChildren = {
  SitesSiteIdActivityRoute: SitesSiteIdActivityRoute,
  SitesSiteIdRulesRoute: SitesSiteIdRulesRoute,
  SitesSiteIdIndexRoute: SitesSiteIdIndexRoute,
}

const SitesSiteIdRouteWithChildren = SitesSiteIdRoute._addFileChildren(
  SitesSiteIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitesSiteIdRoute: SitesSiteIdRouteWithChildren,
  SitesIndexRoute: SitesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
