/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sites */
        get: operations["list_sites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Site */
        get: operations["get_site"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/discoveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Discovery
         * @description Read robots.txt and the sitemaps now (read-only, live) and list the pages.
         */
        post: operations["run_discovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}/page-type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find Page Type
         * @description Which page-type rule matches this URL. Nothing is fetched.
         */
        get: operations["find_page_type"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DiscoveredPage */
        DiscoveredPage: {
            /** Language */
            language: string;
            /** Lastmod */
            lastmod: string;
            /** Page Type */
            page_type: string;
            /** Sitemap */
            sitemap: string;
            /** Url */
            url: string;
        };
        /**
         * DiscoveryRun
         * @description One live discovery: the inventory and every request it made.
         */
        DiscoveryRun: {
            /** Duration Ms */
            duration_ms: number;
            inventory: components["schemas"]["Inventory"];
            /** Requests */
            requests: components["schemas"]["FetchEvent"][];
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** FetchEvent */
        FetchEvent: {
            /** Bytes */
            bytes: number;
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Duration Ms */
            duration_ms: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "robots" | "page";
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "ok" | "redirect" | "too_large" | "cached" | "disallowed" | "blocked" | "error";
            /** Started Ms */
            started_ms: number;
            /** Status */
            status: number | null;
            /** Url */
            url: string;
            /** Waited Ms */
            waited_ms: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Inventory */
        Inventory: {
            /** Base Url */
            base_url: string;
            /** Pages */
            pages: components["schemas"]["DiscoveredPage"][];
            /** Problems */
            problems: components["schemas"]["InventoryProblem"][];
            /** Sitemaps Read */
            sitemaps_read: string[];
        };
        /** InventoryProblem */
        InventoryProblem: {
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "sitemap_blocked" | "sitemap_unreadable" | "sitemap_invalid" | "nested_sitemap_index" | "sitemap_on_other_host" | "url_on_other_host" | "url_not_http" | "duplicate_url";
            /** Url */
            url: string;
        };
        /**
         * PageTypeMatch
         * @description Which rule gives a URL its page type. No match: "other", no rule.
         */
        PageTypeMatch: {
            /** Page Type */
            page_type: string;
            /** Path */
            path: string;
            /** Pattern */
            pattern?: string | null;
            /** Rule Index */
            rule_index?: number | null;
            /** Url */
            url: string;
        };
        /**
         * PageTypeRule
         * @description A URL path pattern and its page type. "*" is exactly one whole path part.
         */
        PageTypeRule: {
            /** Page Type */
            page_type: string;
            /** Pattern */
            pattern: string;
        };
        /**
         * SiteRecord
         * @description A stored site.
         */
        SiteRecord: {
            /** Base Url */
            base_url: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Language */
            language: string;
            /** Page Types */
            page_types: components["schemas"]["PageTypeRule"][];
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Tenant Name */
            tenant_name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_sites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteRecord"][];
                };
            };
        };
    };
    get_site: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_discovery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_page_type: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageTypeMatch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
